// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Clinic.Data.Models;

public partial class Clinic
{
    public int ClinicId { get; set; }

    public string OwnerName { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Contact { get; set; }

    public virtual ICollection<Record> Records { get; set; } = new List<Record>();

    public virtual ICollection<Service> Services { get; set; } = new List<Service>();
}