// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Clinic.Data.Models;

public partial class RecordDetail
{
    public int RecordDetailId { get; set; }

    public int AppointmentDetailId { get; set; }

    public int RecordId { get; set; }

    public string Evaluation { get; set; }

    public string Reccommend { get; set; }

    public virtual AppointmentDetail AppointmentDetail { get; set; }

    public virtual Record Record { get; set; }
}