// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Net1814_212_ASM3_SE183605_TruongMinhNhat.Models;

public partial class Appointment
{
    public int AppointmentId { get; set; }

    public int CustomerId { get; set; }

    public DateOnly Date { get; set; }

    public decimal Total { get; set; }

    public string PaymentMethod { get; set; }

    public bool PaymentStatus { get; set; }

    public string DentistName { get; set; }

    public string Notes { get; set; }

    public bool? Insurance { get; set; }

    public string PatientCondition { get; set; }

    public virtual ICollection<AppointmentDetail> AppointmentDetails { get; set; } = new List<AppointmentDetail>();

    public virtual Customer Customer { get; set; }
}