// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Net1814_212_ASM3_SE183605_TruongMinhNhat.Models;

public partial class RecordDetail
{
    public int RecordDetailId { get; set; }

    public int AppointmentDetailId { get; set; }

    public int RecordId { get; set; }

    public string Evaluation { get; set; }

    public string Reccommend { get; set; }

    public string Diagnosis { get; set; }

    public string Prescriptions { get; set; }

    public string Symptoms { get; set; }

    public string TreatmentPlan { get; set; }

    public string Notes { get; set; }

    public virtual AppointmentDetail AppointmentDetail { get; set; }

    public virtual Record Record { get; set; }
}