// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Net1814_212_ASM3_SE183605_TruongMinhNhat.Models;

public partial class Service
{
    public int ServiceId { get; set; }

    public int ClinicId { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public string Description { get; set; }

    public string Warranty { get; set; }

    public string Duration { get; set; }

    public string Type { get; set; }

    public bool? IsInsuranceAccepted { get; set; }

    public bool? Active { get; set; }

    public virtual ICollection<AppointmentDetail> AppointmentDetails { get; set; } = new List<AppointmentDetail>();

    public virtual Clinic Clinic { get; set; }
}