// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE183605ConsoleEFApp.Models;

public partial class AppointmentDetail
{
    public int AppointmentDetailId { get; set; }

    public int AppointmentId { get; set; }

    public int ServiceId { get; set; }

    public bool IsPeriodic { get; set; }

    public int? Day { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public virtual Appointment Appointment { get; set; }

    public virtual ICollection<RecordDetail> RecordDetails { get; set; } = new List<RecordDetail>();

    public virtual Service Service { get; set; }
}