// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositoriy.Models;

public partial class StaffMember
{
    public int MemberId { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string EmailAddress { get; set; }

    public int? Role { get; set; }
}